version: '3.7'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.1
    container_name: es
    hostname: es2.uggla.fr
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #  - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
