version: '3.7'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.1
    container_name: es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.publish_host=es2.uggla.fr"
      - "discovery.zen.ping.unicast.hosts=es1.uggla.fr"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  esdata:
